version: '3.0'
services:
  cup-api:
    container_name: cup-api
    build:
      context: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    ports:
      - 3500:3500
    deploy:
      restart_policy:
        condition: always
      resources:
        limits:
          memory: 128m
